### ISSUE TITLE
与replay一同使用导致回放中心无法打开

### ISSUE THREAD

**Issue by Ironnoob73** [kappa-maintainer/WrapFix#1]
WrapFix-1.0-beta在与replaymod-1.12.2-2.6.10一同安装使用时，如果回放中心内有录像文件，会导致在打开回放中心时屏幕频闪。
崩溃报告：https://paste.ubuntu.com.cn/4546927

**Comment by kappa-maintainer** [comment]
原来真有人用这个巨型版本啊……
估计是逻辑有疏漏，我看看

**Comment by kappa-maintainer** [comment]
啊这，replay传了个空字符串

**Comment by kappa-maintainer** [comment]
修好了，应该过几个小时就能在cf下到了
