### ISSUE TITLE
聊天栏换行不正确

### ISSUE THREAD

**Issue by Ironnoob73** [kappa-maintainer/WrapFix#2]
![image](https://user-images.githubusercontent.com/67966070/226824770-f48e6590-6b79-47fc-8213-eba4a88ea5b0.png)
![image](https://user-images.githubusercontent.com/67966070/226824828-ac9fa4a8-2fc2-4199-b684-dcf90b1a182c.png)
没有收到任何错误信息

**Comment by kappa-maintainer** [comment]
我看看

**Comment by kappa-maintainer** [comment]
没错误是正常的，这应该是新换行算法的产物

**Comment by kappa-maintainer** [comment]
已经上传了1.0.3，等cf显示吧
原版那段属实是把我搞迷糊了

**Comment by kappa-maintainer** [comment]
可以下载了
