### ISSUE TITLE
聊天栏可互动文本无法互动

### ISSUE THREAD

**Issue by Ironnoob73** [kappa-maintainer/WrapFix#3]
例如截图后聊天栏出现的图片链接无法点击；获得成就时鼠标移至其上也不会显示详细信息等。
（抱歉总是遇到些奇奇怪怪的问题......）

**Comment by kappa-maintainer** [comment]
很正常，本来就是beta
原版排版不管中文就算了，这样的排版还写了两个

**Comment by kappa-maintainer** [comment]
不想努力了，回滚了个早一点的版本
反正又不是在游戏里写Word，应该不会有性能问题……

**Comment by kappa-maintainer** [comment]
Approved了，看看吧
另外有什么会在聊天栏发一大段各种格式文字的模组推荐，我现在写这个苦于没法测试
