### ISSUE TITLE
换行有时会导致特殊符号 § 修改的文本颜色丢失

### ISSUE THREAD

**Issue by KasumiNova** [kappa-maintainer/WrapFix#4]
如题。
未安装模组的情况下，颜色符号可以正常应用。

**Comment by kappa-maintainer** [comment]
这个“有时”能不能给点实例
这个模组应用icu4j后需要大段反复换颜色文本测试，但我也没法覆盖到所有情况，所以一直是beta

**Comment by KasumiNova** [comment]
抱歉，之前的问题我后来手动修改了，后续如果有重复情况会汇报。

另外在打开植物魔法辞典的时候会触发数组越界崩溃，暂时不清楚原因。
https://mclo.gs/pN1H0HH

**Comment by kappa-maintainer** [comment]
[debug.zip](https://github.com/kappa-maintainer/WrapFix/files/12428286/debug.zip)
试试这个，这崩溃有点离奇了

**Comment by KasumiNova** [comment]
使用 debug 版本后，游戏直接无响应了，无法找到相应的崩溃报告。

**Comment by kappa-maintainer** [comment]
发了个新版修植魔崩溃，颜色符号这个还请找找实例
